# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

swear_words = [
	{ word: "arse", tier: "1" },
	{ word: "arses", tier: "1" },
	{ word: "arsehole", tier: "1" },
	{ word: "ass", tier: "1" },
	{ word: "asshole", tier: "1" },
	{ word: "asshat", tier: "1" },
	{ word: "asshats", tier: "1" },
	{ word: "ass-hat", tier: "1" },
	{ word: "ass-hats", tier: "1" },
	{ word: "asses", tier: "1" },
	{ word: "arse", tier: "1" },
	{ word: "assfuck", tier: "3" },
	{ word: "assfucks", tier: "3" },
	{ word: "arse", tier: "1" },
	{ word: "assmonkey", tier: "1" },
	{ word: "assmonkies", tier: "1" },
	{ word: "asswipe", tier: "1" },
	{ word: "bastard", tier: "1" },
	{ word: "bastards", tier: "1" },
	{ word: "bitch", tier: "2" },
	{ word: "bitches", tier: "2" },
	{ word: "bitchy", tier: "2" },
	{ word: "bitchtits", tier: "2" },
	{ word: "bollocks", tier: "1" },
	{ word: "bollox", tier: "1" },
	{ word: "bullshit", tier: "2" },
	{ word: "buttfucka", tier: "3" },
	{ word: "buttfucker", tier: "3" },
	{ word: "buttfuckers", tier: "3" },
	{ word: "clusterfuck", tier: "3" },
	{ word: "cock", tier: "1" },
	{ word: "cocks", tier: "1" },
	{ word: "cocksucker", tier: "2" },
	{ word: "cocksuckers", tier: "2" },
	{ word: "clusterfuck", tier: "3" },
	{ word: "cunt", tier: "3" },
	{ word: "cunts", tier: "3" },
	{ word: "damn", tier: "1" },
	{ word: "damnit", tier: "1" },
	{ word: "dickbag", tier: "2" },
	{ word: "dickhole", tier: "2" },
	{ word: "dipshit", tier: "2" },
	{ word: "dipshits", tier: "2" },
	{ word: "douche", tier: "2" },
	{ word: "douchebag", tier: "2" },
	{ word: "dumbass", tier: "1" },
	{ word: "dumass", tier: "1" },
	{ word: "dumbasses", tier: "1" },
	{ word: "dumbshit", tier: "2" },
	{ word: "dumbshits", tier: "2" },
	{ word: "dumbfuck", tier: "3" },
	{ word: "dumbfucks", tier: "3" },
	{ word: "fag", tier: "3" },
	{ word: "fags", tier: "3" },
	{ word: "faggot", tier: "3" },
	{ word: "faggots", tier: "3" },
	{ word: "fagtard", tier: "3" },
	{ word: "fatass", tier: "1" },
	{ word: "fatasses", tier: "1" },
	{ word: "fuck", tier: "3" },
	{ word: "fucks", tier: "3" },
	{ word: "fucker", tier: "3" },
	{ word: "fuckers", tier: "3" },
	{ word: "fuckass", tier: "3" },
	{ word: "fuckasses", tier: "3" },
	{ word: "fuckboy", tier: "3" },
	{ word: "fuckbutt", tier: "3" },
	{ word: "fucked", tier: "3" },
	{ word: "fuck", tier: "3" },
	{ word: "fuckface", tier: "3" },
	{ word: "fuckin", tier: "3" },
	{ word: "fucking", tier: "3" },
	{ word: "fuckoff", tier: "3" },
	{ word: "fucktard", tier: "3" },
	{ word: "fuckwad", tier: "3" },
	{ word: "gayass", tier: "2" },
	{ word: "gayfuck", tier: "3" },
	{ word: "gaytad", tier: "2" },
	{ word: "goddamn", tier: "2" },
	{ word: "goddamnit", tier: "2" },
	{ word: "hell", tier: "1" },
	{ word: "homo", tier: "2" },
	{ word: "jackass", tier: "1" },
	{ word: "jagoff", tier: "2" },
	{ word: "jackoff", tier: "2" },
	{ word: "jack off", tier: "2" },
	{ word: "jerkoff", tier: "2" },
	{ word: "jerk off", tier: "2" },
	{ word: "kunt", tier: "3" },
	{ word: "lameass", tier: "1" },
	{ word: "lardass", tier: "1" },
	{ word: "mothafucka", tier: "3" },
	{ word: "mothafuckas", tier: "3" },
	{ word: "motherfucker", tier: "3" },
	{ word: "motherfuckers", tier: "3" },
	{ word: "motherfuckin", tier: "3" },
	{ word: "motherfucking", tier: "3" },
	{ word: "pecker", tier: "1" },
	{ word: "piss", tier: "1" },
	{ word: "pissed", tier: "1" },
	{ word: "pussy", tier: "2" },
	{ word: "pussies", tier: "2" },
	{ word: "queer", tier: "3" },
	{ word: "queerbait", tier: "3" },
	{ word: "queers", tier: "3" },
	{ word: "shit", tier: "1" },
	{ word: "shitbag", tier: "2" },
	{ word: "shitbrains", tier: "2" },
	{ word: "shitbreath", tier: "2" },
	{ word: "shitcunt", tier: "3" },
	{ word: "shitface", tier: "2" },
	{ word: "shitfaced", tier: "2" },
	{ word: "shithead", tier: "2" },
	{ word: "shithole", tier: "2" },
	{ word: "shitstain", tier: "2" },
	{ word: "shitter", tier: "2" },
	{ word: "shittiest", tier: "1" },
	{ word: "shitiest", tier: "1" },
	{ word: "shitty", tier: "1" },
	{ word: "twat", tier: "3" },
	{ word: "twats", tier: "3" },
	{ word: "whore", tier: "2" },
	{ word: "whores", tier: "2" }
]

swear_words.each do |hash|
	Swearword.find_or_create_by(word: hash[:word], tier: hash[:tier])
end






